codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "60...100"
  status:
    project:
      default:
        target: 60%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        target: 60%
        threshold: 2%

comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/**/*"
  - "database/migrations/**/*"
  - "src/resources/**/*"
  - "src/config/**/*"
  - "src/assets/**/*"
  - "src/Database/Factories/**/*"
